tests/scripts/pre-validation-deploy-slz-roks-and-obs-instances.sh

Adds random prefix
```
/run pipeline
```

Add random prefix

---

cra-config.yaml
ibm_catalog.json

Update to fscloud profile 1.6.0

---

solutions/instances/main.tf
solutions/instances/variables.tf

https://github.com/terraform-ibm-modules/terraform-ibm-observability-da/issues/17
Update product name in input variables.
```
/run pipeline
```

fix: update input variable name

---

solutions/instances/catalogValidationValues.json.template

In `v1.1.7` the region was made a dropdown picker from the ibm_catalog.json with a default value of `""` so validation is now failing with:
```
2024/04/08 18:10:33 Terraform plan | Error: Invalid value for variable
2024/04/08 18:10:33 Terraform plan | 
2024/04/08 18:10:33 Terraform plan |   on variables.tf line 22:
2024/04/08 18:10:33 Terraform plan |   22: variable "region" {
2024/04/08 18:10:33 Terraform plan |     ├────────────────
2024/04/08 18:10:33 Terraform plan |     │ var.region is ""
2024/04/08 18:10:33 Terraform plan | 
2024/04/08 18:10:33 Terraform plan | The specified region is not a valid selection!
```
The fix is to explicitially pass the region in `catalogValidationValues.json.template` which is used during validation
If the CI pipeline doesn't run when you create the PR, …

Pass the region in catalogValidationValues.json.template

---

solutions/agents/main.tf
solutions/agents/variables.tf
solutions/instances/main.tf
solutions/instances/outputs.tf
solutions/instances/variables.tf
tests/pr_test.go

Issue: https://github.com/terraform-ibm-modules/terraform-ibm-observability-da/issues/32
```
/run pipeline
```

feat: add prefix option to all created resources - DA

---

ibm_catalog.json
solutions/instances/catalogValidationValues.json.template
solutions/instances/main.tf
solutions/instances/variables.tf
tests/pr_test.go

Issue: https://github.com/terraform-ibm-modules/terraform-ibm-observability-da/issues/20, https://github.com/terraform-ibm-modules/terraform-ibm-observability-da/issues/16, https://github.com/terraform-ibm-modules/terraform-ibm-observability-da/issues/44
```
/run pipeline
```
- Include information that users need to know about the PR in the commit message. The commit message …

feat: exposed ability to enable/disable platform metrics/logs, added dropdown and grouped related input variables

---

ibm_catalog.json
solutions/instances/main.tf
solutions/instances/variables.tf

support using an existing monitoring instance for bucket monitoring
https://github.com/terraform-ibm-modules/terraform-ibm-observability-da/issues/89
```
/run pipeline
```

fix: support existing cloud monitoring instance

---

solutions/agents/version.tf
solutions/instances/main.tf
solutions/instances/version.tf
tests/resources/main.tf

enabled COS bucket monitoring and activity tracking by default for instances DA
```
/run pipeline
```

feat: enabled COS bucket monitoring and activity tracking by default for instances DA

---

solutions/instances/main.tf
solutions/instances/outputs.tf
solutions/instances/variables.tf

Issue: https://github.com/terraform-ibm-modules/terraform-ibm-observability-da/issues/132
```
/run pipeline
```

feat: skip cos creation when archive and routing is false

---

ibm_catalog.json
solutions/instances/README.md
solutions/instances/main.tf
solutions/instances/variables.tf

`enable_platform_logs` can now work with cloud logs
```
/run pipeline
```

feat: added support to enable platform logs in cloud logs region using boolean

---

solutions/instances/main.tf
solutions/instances/outputs.tf
solutions/instances/variables.tf
tests/pr_test.go

added the ability to continue managing the log archiving bucket even after log archiving has been disabled or logdna has been deleted using new input `manage_log_archive_cos_bucket`
```
/run pipeline
```
- Use the **Squash and merge** …

feat: add the ability to continue managing the log archiving bucket even after log archiving has been disabled or logdna has been deleted

---

tests/pr_test.go

re-enable multiple EN integrations in test
```
/run pipeline
```

test: re-enable multiple EN integrations in test

---

solutions/agents/main.tf
solutions/agents/variables.tf

issue: https://github.ibm.com/GoldenEye/issues/issues/11264
```
/run pipeline
```

feat: add support for container filter

---

solutions/agents/main.tf
solutions/agents/provider.tf

Fix for these issues:
- https://github.com/terraform-ibm-modules/terraform-ibm-observability-da/issues/223
- https://github.com/terraform-ibm-modules/terraform-ibm-observability-da/issues/222
```
/run pipeline
```
- Use the **Squash and …

fix: cluster ID fix and helm provider config update

---

solutions/agents/provider.tf

fix: add `cluster_ca_certificate` to the kube provider config

---

solutions/instances/catalogValidationValues.json.template

We are getting name clash, so adding a prefix:
`"message": "Your request has failed because the requested name cloud-monitoring-target already exists. Use a different name."`
```
/run pipeline
```

ci: add prefix value to catalogValidationValues.json.template

---

solutions/instances/main.tf
solutions/instances/outputs.tf

Issue: https://github.ibm.com/GoldenEye/issues/issues/12121
Updates the condition while setting up metric router target & route so that it doesn't fail when existing `cloud_monitoring_crn` is inputed.
```
/run pipeline
```
- Use the …

Resolves validation failure on providing Cloud monitoring crn

---

solutions/instances/outputs.tf

Need these outputs in the RAG stack to support adding log agents in the ocp cluster.
Issue: https://github.com/terraform-ibm-modules/stack-retrieval-augmented-generation/issues/219
```
/run pipeline
```
- Use the **Squash and merge** …

feat: add additional cloud logs output

---

tests/pr_test.go
tests/resources/existing-resources/main.tf
tests/resources/existing-resources/outputs.tf

The [ExistingResourcesInstances](https://github.com/terraform-ibm-modules/terraform-ibm-observability-da/blob/23746d185151ec200e843adfeeebd74ba3e9984e/tests/pr_test.go#L219) has been updated so that it can check the case where users give `cloud_monitoring_crn` as input.
Resolves: https://github.com/terraform-ibm-modules/terraform-ibm-observability-da/issues/247
The [ExistingResourcesInstances](https://github.com/terraform-ibm-modules/terraform-ibm-observability-da/blob/23746d185151ec200e843adfeeebd74ba3e9984e/tests/pr_test.go#L219) has been updated so that it can check the case where users give `cloud_monitoring_crn` as input, preventing the validation failure for  release [v2.6.2](https://github.com/terraform-ibm-modules/terraform-ibm-observability-da/releases/tag/v2.6.2).
If the CI …

fix: update ExistingResourceInstances test

---

solutions/instances/main.tf

Issue: https://github.com/terraform-ibm-modules/terraform-ibm-observability-instances/issues/621
```
/run pipeline
```

fix(deps): update observability instance module version

---

tests/pr_test.go

test: update test to use correct region

---

README.md

Updated the readme to remove disclaimer in readme
Resolves: #272 
```
/run pipeline
```

remove disclaimer in readme

---

tests/resources/version.tf

add workaround for provider breaking change

---

tests/resources/main.tf

bump slz version used in tests

---

solutions/agents/version.tf
solutions/instances/version.tf
solutions/logs-routing/version.tf
tests/resources/existing-resources/version.tf
tests/resources/version.tf

chore: bump provider version

---

solutions/instances/catalogValidationValues.json.template

Catalog validation failing due to the fact there is already an instance with platform metrics enabled
```
/run pipeline
```

Update catalogValidationValues.json.template to disable platform metrics

---

ibm_catalog.json
solutions/instances/catalogValidationValues.json.template
solutions/instances/main.tf
solutions/instances/variables.tf
tests/pr_test.go

Resolves: https://github.com/terraform-ibm-modules/terraform-ibm-observability-da/issues/289
```
/run pipeline
```

add metrics router primary_metadata_region in the observability DA

---

solutions/instances/main.tf

We can't hard code to `eu-de` because it will clash with var.region if that was set to `eu-de`. Backup region is not required, so going to remove it. User can explicitly add it with the `metrics_router_settings` if they want.
```
Error: UpdateSettingsWithContext failed The backup region cannot be the same as the primary region. Valid regions for MetadataRegionBackup are: [eu-gb au-syd us-east us-south eu-es eu-fr2 br-sao ca-tor jp-osa jp-tok].  Your primary region is currently set to eu-de.
```
```
/run pipeline
```
- Use a …

fix: remove `backup_metadata_region` to avoid clash with `primary_metadata_region`

---

solutions/instances/main.tf

Even though we're only doing a comparison (var.ibmcloud_cos_api_key != null), Terraform treats the entire value as "tainted" by sensitivity. Consequently we can not do `for_each` against sensitive input.
Since we’re not exposing any secrets — just a true/false based on the presence of a sensitive var — we can wrap it with nonsensitive()
```
/run pipeline
```
- Include …

fix: use nonsensitive for api_key comparison

---

cra-config.yaml
ibm_catalog.json
solutions/instances/catalogValidationValues.json.template
solutions/instances/variables.tf
tests/pr_test.go

fix: Align terraform input values with catalog manifest values and update tests

---

solutions/agents/version.tf
solutions/instances/version.tf
solutions/logs-routing/version.tf

Fix for https://github.com/IBM-Cloud/terraform-provider-ibm/issues/6269
Internal Issue: [14162](https://github.ibm.com/GoldenEye/issues/issues/14162)
```
/run pipeline
```

fix(deps): bump to ibm provider 1.79.0 

---

solutions/instances/main.tf

Update event_notification input to match with cloud_logs inputs
```
/run pipeline
```

fix: Update event_notification input to match with cloud_logs inputs
